### ISSUE TITLE
Bower install issue

### ISSUE THREAD

**Issue by NikolaBreznjak** [rajeshwarpatlolla/ionic-toast#3]
Hey,

I would first like to thank you that you have taken the time to create this plugin.

However, I ran into an issue when trying to install it with Bower, and I hope you can help:

module.js:338
    throw err;
          ^
Error: Cannot find module 'insight'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at ensureInsight (C:\Users\Nikola\AppData\Roaming\npm\node_modules\bower\lib\util\analytics.js:24:23)
    at Object.setup (C:\Users\Nikola\AppData\Roaming\npm\node_modules\bower\lib\util\analytics.js:41:9)
    at Object.<anonymous> (C:\Users\Nikola\AppData\Roaming\npm\node_modules\bower\bin\bower:72:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by rajeshwarpatlolla** [comment]
I think, you need to check the version of npm, node and bower. Update them and try installing them again.

**Comment by NikolaBreznjak** [comment]
Actually, I downloaded the project manually. Great work btw. However, I was wondering how come the closing function needs to be added to the controller? Couldn't it be somehow solved without it, by placing the closing timeout into the plugin? I mean, I'm not complaining, just curious.

**Comment by rajeshwarpatlolla** [comment]
You can use the `stick` property mentioned in the repository description. If you set it to true, you will be able to see the close button in the toaster or else it will close after some time automatically. Even you will be able to give the time as one of the property.
